branches:
  only:
  - /.*/
language: ruby
sudo: false
rvm: 2.2
addons:
  apt:
    packages:
    - oracle-java8-installer
cache:
  - bundler
  - directories:
    - $HOME/.ivy2
    - $HOME/.sbt
    - $HOME/.gem
    - $HOME/.local
    - $PWD/node_modules
before_install: ./.ci_scripts/beforeInstall.sh 0.13.11
script:
  - ./.ci_scripts/validate.sh 0.13.11
  - bundle exec jekyll serve --detach && echo "# Jekyll local server started"
  - ./.ci_scripts/consolidate.sh
