highlighter: true
name: "ReactiveMongo"
description: "The reactive Scala driver for MongoDB"
url: http://reactivemongo.org/
markdown: kramdown
latest_major_release: 0.1x
latest_release: 0.20.11
exclude: [vendor,target]
plugins:
  - jekyll-sitemap
  - jekyll-algolia

_0_11_latest_minor: 0.11.14
_0_12_latest_minor: 0.12.4

_0_1x_latest_major: 0.20
_0_1x_latest_minor: 0.20.11
_0_1x_scala_major: 2.12

_1_0_latest_major: 1.0
_1_0_latest_minor: 1.0.0-rc.1
_1_0_scala_major: 2.13

algolia:
  application_id: 'Y0CQ010OIG'
  index_name: 'reactivemongo'
  search_only_api_key: 'ab9de0dae62c589128703e9076090b2f'
  nodes_to_index: '#main p, #main > ul'
  settings:
    attributesForFaceting: ['major_version']
