pygments: true
name: "ReactiveMongo"
description: "The reactive Scala driver for MongoDB"
url: http://reactivemongo.org/
markdown: kramdown
latest_major_release: 0.11
latest_release: 0.11.1

gems:
  - jekyll-redirect-from
