pygments: true
name: "ReactiveMongo"
description: "The reactive Scala driver for MongoDB"
url: http://reactivemongo.org/
markdown: kramdown
latest_major_release: 0.13
latest_release: 0.13.0
exclude: [vendor,target]
gems:
  - jekyll-sitemap
  - algoliasearch-jekyll

_0_11_latest_minor: 0.11.14
_0_12_latest_minor: 0.12.6
_0_13_latest_minor: 0.13.0

algolia:
  application_id: 'LZ1F244Z01'
  search_only_api_key: 'b0690010c443bd4632a6bba0ac8d26bd'
  record_css_selector: 'p,ul'
  settings:
    attributesForFaceting: ['#majorVersion']
